version: '3'

services:
  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - '8080:8080'

  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
